services:
  nginx:
    image: nginx:alpine
    container_name: bigdata-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - bigdata-frontend
      - bigdata-backend

  bigdata-frontend:
    build:
      context: ../web
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: "http://localhost/covid"
        NEXT_PUBLIC_ENV: "production"
    container_name: bigdata-frontend

  bigdata-backend:
    build:
      context: ../api
      dockerfile: Dockerfile
    container_name: bigdata-backend
